### ISSUE TITLE
Cannot resolve "http://central.maven.org/maven2/" because does not exist

### ISSUE THREAD

**Issue by benavid** [vaadin/framework8-migration-tool#61] opened 2022-07-01 14:51 UTC
First time that you run mvn clean install, test cases fail beacuse can not dowload the artifact from maven respository.
This is due to http://central.maven.org/maven2/ maven respository does not exist so if you replace this by for example https://repo1.maven.org/maven2/ the test cases pass and you can generate the migration tool jar

**Comment by Legioth** [comment] 2022-08-04 07:19
Duplicate of https://github.com/vaadin/framework8-migration-tool/issues/56 for which I just merged an old and forgotten fix. 

We'll still have to dig through some archives to understand how a new version is released :)

**Closed** 2022-08-04 07:19 UTC

**Comment by Legioth** [comment] 2022-08-04 07:22
Oh right, not releasing at all since we folded this functionality into the regular Maven plugin a good while ago.
